### ISSUE TITLE
Amoy testnet heimdall 1.0.10/1.1.0-beta broke before jorvikhardfork height

### ISSUE THREAD

**Issue by jun0tpyrc** [maticnetwork/heimdall#1209]
consensus layer height=5768654
47FE8530728F28365D236037AC55243299866FBABF2D937C871D3F4221FC8861 from 1.0.10
A25F11AAE04A089E9DCE70CA8827FF54BDAF398F22A26DF5F58259AACD47DE2D from 1.1.0-beta
expected FAE7FDF9DA93BCEB584E8DC34F7498FD5AD7CD0206D346560D5B77B53068CBCA

**Comment by DaraDoyoung** [comment]
having same issue. did you solve it?

**Comment by DaraDoyoung** [comment]
@jun0tpyrc the chain is already hardforked. it happened 5h ago.

**Comment by jajaislanina** [comment]
Once we hit this error we had to download the snapshot for heimdall and start the node again.
We had disabled _bor__ namespace on Bor so some methods failed from heimdall and resulted in corrupt state.

**Comment by jun0tpyrc** [comment]
> Once we hit this error we had to download the snapshot for heimdall and start the node again. We had disabled _bor__ namespace on Bor so some methods failed from heimdall and resulted in corrupt state.

not very understanding this , so you succeeded with recover?!
even on 1.1.0-beta reworked with https://snapshots.publicnode.com/polygon-amoy-heimdall-5767815.tar.lz4 (before problem height) seems hitting same problem

**Comment by jajaislanina** [comment]
well, kind of. recovered for a few thousand blocks but then hit the issue again.

**Comment by matthewdarwin** [comment]
Here is the error we got.

```
panic: Failed to process committed block (5768655:A25F11AAE04A089E9DCE70CA8827FF54BDAF398F22A26DF5F58259AACD47DE2D): Wrong Block.Header.AppHash.  Expected DD5B3758C3C058AB988523275DD1025591EDF11334DE31DEA578F91C59239164, got FAE7FDF9DA93BCEB584E8DC34F7498FD5AD7CD0206D346560D5B77B53068CBCA
goroutine 117 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc001503180)
#011/home/runner/go/pkg/mod/github.com/maticnetwork/tendermint@v0.33.2/blockchain/v0/reactor.go:344 +0xfa5
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart in goroutine 1
#011/home/runner/go/pkg/mod/github.com/maticnetwork/tendermint@v0.33.2/blockchain/v0/reactor.go:118 +0x6e
```

**Comment by jajaislanina** [comment]
Got it running. Switched Heimdall to external bor `bor_rpc_url = "https://rpc-amoy.polygon.technology"`
Node synced to HEAD and now switched to our Bor. 
Works again fine.

**Comment by jun0tpyrc** [comment]
updating

> `bor_rpc_url = "https://rpc-amoy.polygon.technology"`

in config/heimdall-config.toml

^
looks only with this line it becomes working, we have never unplugged both ws/http's bor namespace api but we still hit this in different combinations before switchinging to this bor_rpc_url

**Comment by matthewdarwin** [comment]
@jun0tpyrc I confirm your solution works.

**Comment by calinah** [comment]
Also experiencing the same error:
```
│ heimdall ERROR: failed to create new node: error during handshake: error on replay: Wrong Block.Header.AppHash.  Expected 47FE8530728F28365D236037AC55243299866FBABF2D937C871D3F4221FC8861, got FAE7FDF9DA93BCEB584E8DC34F7498FD5AD7CD0206D346560D5B77B53068CBCA

**Comment by avalkov** [comment]
@calinah Please make sure your using v1.1.0-beta and take snapshot from here https://publicnode.com/snapshots#polygon 
You need your bor to be in sync if its not you can use https://rpc-amoy.polygon.technology/ until it catches up.

**Comment by calinah** [comment]
thank you @avalkov you suggestion fixed my issues

**Comment by icculp** [comment]
I'm a bit confused by this, doesn't bor need heimdall to sync? But now heimdall needs bor synced, before heimdall can sync, before bor can sync from heimdall?

**Comment by marcello33** [comment]
Hi @icculp,

When syncing from genesis without using a snapshot, the blocks in the `[Jorvik, HFn]` range require `bor` to be in sync. `HFn` refers to the upcoming hardfork on the Amoy network, which is scheduled for early January 2025 and will resolve this issue.
This problem will not occur on the mainnet, as a hardfork is expected there, likely in early February 2025. 
Additionally, with the comprehensive refactoring of Heimdall-v2 currently underway (targeted for release in Q1 2025), this issue will no longer affect any network.

Thank you
