### ISSUE TITLE
`heimdallcli generate-validatorkey` unable to create new validator key

### ISSUE THREAD

**Issue by svenski123** [maticnetwork/heimdall#284]
Heimdall built off of branch cs-2005, commit 6b515f0d41558d02133b957c32817e03432d8a22

My validator address in CS-2005 is 0x2E2de368D26A56445875D56D6Ad55aa5C896F112.

I deleted the `~/.heimdalld/config/priv_validator_key.json` file produced by `heimdalld init` and attempted to generate a new validator key but was not able to do so.

The `heimdallcli generate-validatorkey` command cannot generate a new key unless an old one already exists in the heimdall config directory.

This tool should not require the existence of a previous key to generate a new one and it should not seg fault.

```
[matic@ml150 ~]$ rm ~/.heimdalld/config/priv_validator_key.json
[matic@ml150 ~]$ heimdallcli generate-validatorkey "$KEY2"
open /home/matic/.heimdalld/config/priv_validator_key.json: no such file or directory
[matic@ml150 ~]$ stat priv_validator_key.json
stat: cannot stat ‘priv_validator_key.json’: No such file or directory
```

Creating an empty `.heimdalld/config/priv_validator_key.json` file display the following error:
```
[matic@ml150 ~]$ echo '' > /home/matic/.heimdalld/config/priv_validator_key.json
[matic@ml150 ~]$ heimdallcli generate-validatorkey "$KEY2"
Error reading PrivValidator key from /home/matic/.heimdalld/config/priv_validator_key.json: unexpected end of JSON input

[matic@ml150 ~]$ stat priv_validator_key.json
stat: cannot stat ‘priv_validator_key.json’: No such file or directory
```

Writing an empty JSON object to `.heimdalld/config/priv_validator_key.json` file causes `heimdallcli generate-validator key` to seg fault:
```
[matic@ml150 ~]$ echo '{}' > /home/matic/.heimdalld/config/priv_validator_key.json
[matic@ml150 ~]$ heimdallcli generate-validatorkey "$KEY2"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc5733d]

goroutine 1 [running]:
github.com/tendermint/tendermint/privval.loadFilePV(0xc0001a7880, 0x35, 0xc0001a78c0, 0x35, 0x1, 0x0)
        /home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/privval/file.go:187 +0xfd
github.com/tendermint/tendermint/privval.LoadFilePV(...)
        /home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/privval/file.go:165
github.com/maticnetwork/heimdall/helper.InitHeimdallConfigWith(0xc00069bc60, 0x16, 0x0, 0x0)
        /home/matic/go/src/github.com/maticnetwork/heimdall/helper/config.go:199 +0x768
github.com/maticnetwork/heimdall/helper.InitHeimdallConfig(0xc00069bc60, 0x16)
        /home/matic/go/src/github.com/maticnetwork/heimdall/helper/config.go:149 +0xc8
main.initTendermintViperConfig(0xc000259680)
        /home/matic/go/src/github.com/maticnetwork/heimdall/cmd/heimdallcli/main.go:68 +0x1f5
main.glob..func1(0xc000259680, 0xc0001c9b20, 0x1, 0x1, 0x0, 0x0)
        /home/matic/go/src/github.com/maticnetwork/heimdall/cmd/heimdallcli/main.go:51 +0x2b
github.com/tendermint/tendermint/libs/cli.concatCobraCmdFuncs.func1(0xc000259680, 0xc0001c9b20, 0x1, 0x1, 0x0, 0x0)
        /home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/libs/cli/setup.go:115 +0x7d
github.com/tendermint/tendermint/libs/cli.concatCobraCmdFuncs.func1(0xc000259680, 0xc0001c9b20, 0x1, 0x1, 0x0, 0x0)
        /home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/libs/cli/setup.go:115 +0x7d
github.com/spf13/cobra.(*Command).execute(0xc000259680, 0xc0001c9af0, 0x1, 0x1, 0xc000259680, 0xc0001c9af0)
        /home/matic/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:805 +0x56b
github.com/spf13/cobra.(*Command).ExecuteC(0x24bccc0, 0x872be0, 0x24bccc0, 0x142f4c4)
        /home/matic/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/matic/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x24bccc0, 0x1670640, 0x2, 0xc00069bc60)
        /home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20200105181728-9b2d312d5d14/libs/cli/setup.go:89 +0x3c
main.main()
        /home/matic/go/src/github.com/maticnetwork/heimdall/cmd/heimdallcli/main.go:123 +0x4fe
[matic@ml150 ~]$ stat priv_validator_key.json
stat: cannot stat ‘priv_validator_key.json’: No such file or directory
```

**Comment by myvidster** [comment]
It looks like they merged heimdallcli with heimdall.  So do something like this.
heimdalld generate-validatorkey <Your Ethereum wallet *private* key>

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if issue still persists
