### ISSUE TITLE
Bor chain halting after one sprint due to checkpoint submission to root chain failing in heimdall-bridge

### ISSUE THREAD

**Issue by ssandeep** [maticnetwork/heimdall#645]
Steps to reproduce (with single node, in local):
1. Reset heimdalld, bridge, bor and start them
2. After 64 blocks in bor, it starts complaining about span/1 not being available:
```
INFO [04-18|15:05:53.001] Commit new mining work                   number=63 sealhash="730def…3fac3d" uncles=0 txs=0 gas=0 fees=0 elapsed="945.989µs"
INFO [04-18|15:05:54.001] Sealing successful                       number=63 delay=997.92ms   headerDifficulty=1
INFO [04-18|15:05:54.001] Successfully sealed new block            number=63 sealhash="730def…3fac3d" hash="fbbe3a…6ceae9" elapsed=999.785ms
INFO [04-18|15:05:54.001] 🔗 block reached canonical chain          number=56 hash="6ba5f0…22e67e"
INFO [04-18|15:05:54.001] 🔨 mined potential block                  number=63 hash="fbbe3a…6ceae9"
INFO [04-18|15:05:54.005] Retrying again in 5 seconds for next Heimdall span path=heimdall/bor/v1beta1/span/1
INFO [04-18|15:05:59.008] Retrying again in 5 seconds for next Heimdall span path=heimdall/bor/v1beta1/span/1
```
3. In the bridge logs, there is an error after preparing checkpoint to be pushed on chain (in GetSideTxSigs):
```
E[2021-04-18|15:08:53.487] Error while Unsubscribe the tm.event='NewBlock' the subscriber  Subscriber=new-block-0 Err=null
E[2021-04-18|15:08:53.487] Error fetching begin block events            module=heimdall service=listener error="timed out waiting for event"
I[2021-04-18|15:08:53.518] Fetching new events between                  module=heimdall service=listener fromBlock=24 toBlock=46
I[2021-04-18|15:09:53.372] Fetching new events between                  module=heimdall service=listener fromBlock=47 toBlock=58
I[2021-04-18|15:09:53.378] Query rootchain event logs                   module=rootchain service=listener fromBlock=8452 toBlock=8463
I[2021-04-18|15:10:53.359] Fetching new events between                  module=heimdall service=listener fromBlock=59 toBlock=70
I[2021-04-18|15:10:53.364] Query rootchain event logs                   module=rootchain service=listener fromBlock=8464 toBlock=8475
D[2021-04-18|15:10:53.417] Error while fetching data from URL           status=500 URL="http://0.0.0.0:1317/heimdall/bor/v1beta1/prepare-next-span?bor_chain_id=15001&proposer=0xf3d853dbaa6f5f2e42172d37eb39b9895f810541&span_id=1&start_block=256"
E[2021-04-18|15:10:53.418] Error fetching proposers                     error="error while fetching data from url: http://0.0.0.0:1317/heimdall/bor/v1beta1/prepare-next-span?bor_chain_id=15001&proposer=0xf3d853dbaa6f5f2e42172d37eb39b9895f810541&span_id=1&start_block=256, status: 500"
E[2021-04-18|15:10:53.418] Error while sending request for next span details error="error while fetching data from url: http://0.0.0.0:1317/heimdall/bor/v1beta1/prepare-next-span?bor_chain_id=15001&proposer=0xf3d853dbaa6f5f2e42172d37eb39b9895f810541&span_id=1&start_block=256, status: 500"
I[2021-04-18|15:10:53.724] Processing new header                        module=checkpoint service=processor headerNumber=63
I[2021-04-18|15:10:53.856] Force push checkpoint                        module=checkpoint service=processor currentTime=1618738853 lastCheckpointTime=0 defaultForcePushInterval=2048 start=0 end=62
D[2021-04-18|15:10:53.858] Error while fetching data from URL           status=500 URL=http://0.0.0.0:1317/heimdall/checkpoint/v1beta1/buffer
I[2021-04-18|15:10:53.879] Root hash calculated                         module=checkpoint service=processor rootHash=0xf4268ca7773f4f924dcd276fd3881e5cdac8acfac68b6863909afeb70f12aa70
I[2021-04-18|15:10:53.880] Sending Rest call to Get Dividend AccountRootHash module=checkpoint service=processor
I[2021-04-18|15:10:53.885] Divident account root fetched                module=checkpoint service=processor
I[2021-04-18|15:10:53.886] ✅ Creating and broadcasting new checkpoint   module=checkpoint service=processor start=0 end=62 root=0xf4268ca7773f4f924dcd276fd3881e5cdac8acfac68b6863909afeb70f12aa70 accountRoot=0xb4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d30
D[2021-04-18|15:10:53.921] Broadcasting tx bytes to Tendermint          txBytes=0aef010aec010a2a2f6865696d64616c6c2e636865636b706f696e742e763162657461312e4d7367436865636b706f696e7412bd010a2a307866336438353364626161366635663265343231373264333765623339623938393566383130353431183e22423078663432363863613737373366346639323464636432373666643338383165356364616338616366616336386236383633393039616665623730663132616137302a423078623463313139353139353763366638663634326334616636316364366232343634306665633664633766633630376565383230366139396539323431306433303205313530303112560a4e0a460a1f2f636f736d6f732e63727970746f2e736563703235366b312e5075624b657912230a2103d8abb4e7c1b75ab80fd868954327b061b4f5aaccac3ff640d7b0b4659826e78c12040a020801120410c09a0c1a41ee0be2cb9a587617a7fae97e7de494c23c048fc9dba1ee71dfede3714a4fc7823c33a5d65214508fd03407307df53f37ff59d8d6a55658843edd76b3737f463e01 txHash=783a1f49dd4cad8f829af451ae0e87a64ca2ea16ae07a0ad4c78b03e519598c3
I[2021-04-18|15:10:53.958] Tx sent on heimdall                          module=txBroadcaster txHash=783A1F49DD4CAD8F829AF451AE0E87A64CA2EA16AE07A0AD4C78B03E519598C3 accSeq=0 accNum=0
I[2021-04-18|15:11:53.355] Fetching new events between                  module=heimdall service=listener fromBlock=71 toBlock=81
I[2021-04-18|15:11:53.359] Query rootchain event logs                   module=rootchain service=listener fromBlock=8476 toBlock=8487
I[2021-04-18|15:11:53.364] Received block event from Heimdall           module=heimdall service=listener eventType=checkpoint
I[2021-04-18|15:11:53.364] Sending block level task                     module=heimdall service=listener taskName=sendCheckpointToRootchain currentTime=2021-04-18T15:11:53.364543+05:30 blockHeight=73
I[2021-04-18|15:11:53.445] Received sendCheckpointToRootchain request   module=checkpoint service=processor eventBytes="{\"type\":\"checkpoint\",\"attributes\":[{\"key\":\"action\",\"value\":\"checkpoint\"},{\"key\":\"module\",\"value\":\"checkpoint\"},{\"key\":\"txhash\",\"value\":\"0x783a1f49dd4cad8f829af451ae0e87a64ca2ea16ae07a0ad4c78b03e519598c3\"},{\"key\":\"side-tx-result\",\"value\":\"YES\"},{\"key\":\"proposer\",\"value\":\"0xf3d853dbaa6f5f2e42172d37eb39b9895f810541\"},{\"key\":\"start-block\",\"value\":\"0\"},{\"key\":\"end-block\",\"value\":\"62\"},{\"key\":\"root-hash\",\"value\":\"0xf4268ca7773f4f924dcd276fd3881e5cdac8acfac68b6863909afeb70f12aa70\"},{\"key\":\"account-hash\",\"value\":\"0xb4c11951957c6f8f642c4af61cd6b24640fec6dc7fc607ee8206a99e92410d30\"}]}" blockHeight=73
I[2021-04-18|15:11:53.447] processing checkpoint confirmation event     module=checkpoint service=processor eventtype=checkpoint
I[2021-04-18|15:11:53.469] Validating if checkpoint needs to be pushed  module=checkpoint service=processor commitedLastBlock=0 startBlock=0
I[2021-04-18|15:11:53.469] Checkpoint Valid                             module=checkpoint service=processor startBlock=0
I[2021-04-18|15:11:53.469] Preparing checkpoint to be pushed on chain   module=checkpoint service=processor height=73 txHash=0x783a1f49dd4cad8f829af451ae0e87a64ca2ea16ae07a0ad4c78b03e519598c3 start=0 end=62
ERROR: 2021/04/18 15:11:53 task.go:130 goroutine 195 [running]:
runtime/debug.Stack(0x71e3940, 0xc00075e880, 0x2)
	runtime/debug/stack.go:24 +0x9f
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call.func1(0xc0018ab630, 0xc0010ca190)
	github.com/RichardKnop/machinery@v1.10.0/v1/tasks/task.go:130 +0xc5
panic(0x59d9c40, 0xc00067f240)
	runtime/panic.go:969 +0x1b9
github.com/tendermint/tendermint/crypto/secp256k1.PubKey.Address(0x0, 0x0, 0x0, 0xc000049220, 0x41, 0x42)
	github.com/tendermint/tendermint@v0.34.8/crypto/secp256k1/ethsecp256k1.go:116 +0xf9
github.com/maticnetwork/heimdall/helper.GetSideTxSigs(0xc0013ea4a0, 0x20, 0x20, 0xc00080c300, 0xc0, 0x100, 0xc0001a23f0, 0x1, 0x1, 0x0, ...)
	github.com/maticnetwork/heimdall/helper/util.go:401 +0x225
github.com/maticnetwork/heimdall/helper.FetchSideTxSigs(0xc0010962d0, 0x49, 0xc0013ea4a0, 0x20, 0x20, 0xc00080c300, 0xc0, 0x100, 0xc001145cd0, 0x630ec00, ...)
	github.com/maticnetwork/heimdall/helper/query.go:158 +0xf8
github.com/maticnetwork/heimdall/bridge/setu/processor.(*CheckpointProcessor).createAndSendCheckpointToRootchain(0xc00073c600, 0xc0006d8960, 0xc001c7a700, 0x0, 0x3e, 0x49, 0xc001a473c0, 0x20, 0x40, 0x630ec00, ...)
	github.com/maticnetwork/heimdall/bridge/setu/processor/checkpoint.go:502 +0x912
github.com/maticnetwork/heimdall/bridge/setu/processor.(*CheckpointProcessor).sendCheckpointToRootchain(0xc00073c600, 0xc00020c780, 0x245, 0x49, 0xc000740000, 0x40195db)
	github.com/maticnetwork/heimdall/bridge/setu/processor/checkpoint.go:223 +0x736
reflect.Value.call(0x59cbcc0, 0xc00067e5c0, 0x13, 0x5cdbab3, 0x4, 0xc0013ba3f0, 0x2, 0x2, 0x5b7a4c0, 0x5c05ae0, ...)
	reflect/value.go:476 +0x8c7
reflect.Value.Call(0x59cbcc0, 0xc00067e5c0, 0x13, 0xc0013ba3f0, 0x2, 0x2, 0xc0013ba450, 0xc00062c150, 0xc000690ee8)
	reflect/value.go:337 +0xb9
github.com/RichardKnop/machinery/v1/tasks.(*Task).Call(0xc0010ca190, 0x0, 0x0, 0x0, 0x62c25e0, 0xc00067f240)
	github.com/RichardKnop/machinery@v1.10.0/v1/tasks/task.go:142 +0x276
github.com/RichardKnop/machinery/v1.(*Worker).Process(0xc000164a50, 0xc0010f8000, 0x0, 0x0)
	github.com/RichardKnop/machinery@v1.10.0/v1/worker.go:182 +0x386
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consumeOne(0xc0000966c0, 0x62f70c0, 0xc000654000, 0x0, 0xc0010b8080, 0x10, 0x0, 0x0, 0x2, 0x0, ...)
	github.com/RichardKnop/machinery@v1.10.0/v1/brokers/amqp/amqp.go:336 +0x4f2
github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume.func2(0xc0000966c0, 0xc0010983c0, 0x62ebe40, 0xc000164a50, 0xc00053c600, 0xa, 0xc0005420c0)
	github.com/RichardKnop/machinery@v1.10.0/v1/brokers/amqp/amqp.go:286 +0xe5
created by github.com/RichardKnop/machinery/v1/brokers/amqp.(*Broker).consume
	github.com/RichardKnop/machinery@v1.10.0/v1/brokers/amqp/amqp.go:285 +0x135

WARNING: 2021/04/18 15:11:53 worker.go:220 Task task_11aeec16-0fe6-4567-9a35-32b6a0369298 failed. Going to retry in 1 seconds.
```

**Comment by temaniarpit27** [comment]
Heimdall V2 issue
Closing this
