### ISSUE TITLE
panic: Any JSON doesn't have '@type'

### ISSUE THREAD

**Issue by nuliknol** [maticnetwork/heimdall#692]
Heimdall version: 0.3.0-370-g0f060e0e

**Environment**:
OS: Ubuntu 18.04
Golang : 1.16.4

Heimdall crashes on `heimdalld start`

```
matic@ubuntu:~/h$ ./heimdalld start

I[2021-06-03|22:56:30.095] starting ABCI with Tendermint                module=main 
panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc000e4c300, 0xc0002da500, 0x4a9, 0x500, 0x21ba408, 0xc000144600)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/codec/proto_codec.go:159 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x21b08f0, 0xc000e4cab0, 0x7fa6fc334c28, 0xc000e4c300, 0x7fa6fc334c28, 0xc000e4c300, 0xc0000100a0, 0x21b08f0, 0xc000e4cb30, 0x21b0940, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/x/auth/module.go:138 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000138e00, 0x21cb028, 0xc000048120, 0x21dee88, 0xc000144340, 0x0, 0x0, 0xc00068e790, 0xe, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/types/module/module.go:304 +0x2b5
github.com/maticnetwork/heimdall/app.(*HeimdallApp).InitChainer(0xc00023e000, 0x21cb028, 0xc000048120, 0x21dee88, 0xc000144340, 0x0, 0x0, 0xc00068e790, 0xe, 0x0, ...)
	/home/matic/sources/heimdall/app/app.go:595 +0x270
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00012d6c0, 0x3014bb28, 0xed66ac838, 0x0, 0xc00068e790, 0xe, 0xc0010ac0e0, 0x30dec38, 0x0, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/baseapp/abci.go:62 +0x2f5
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000e0c900, 0x3014bb28, 0xed66ac838, 0x0, 0xc00068e790, 0xe, 0xc0010ac0e0, 0x30dec38, 0x0, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/abci/client/local_client.go:247 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc0005c6e00, 0x3014bb28, 0xed66ac838, 0x0, 0xc00068e790, 0xe, 0xc0010ac0e0, 0x30dec38, 0x0, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/proxy/app_conn.go:78 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc00143e630, 0xb, 0x0, 0x0, 0x0, 0xc00068e790, 0xe, 0x1, 0x0, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00143e630, 0x21e2c78, 0xc000ff6a90, 0xc36fe5, 0x203000)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/consensus/replay.go:268 +0x4bc
github.com/tendermint/tendermint/node.doHandshake(0x21deef0, 0xc0005c6b80, 0xb, 0x0, 0x0, 0x0, 0xc00068e790, 0xe, 0x1, 0x0, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/node/node.go:277 +0x19b
github.com/tendermint/tendermint/node.NewNode(0xc00111a280, 0x21cb878, 0xc00013efa0, 0xc0000bb400, 0x2192c00, 0xc000692180, 0xc0000bb830, 0x1f1ec18, 0xc0000bbe30, 0x21cb760, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20210419165356-d045b7a4e8fd/node/node.go:685 +0x1dda
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0010ad0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x21cb1b0, 0xc00107e400, ...)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/server/start.go:236 +0x5f7
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00110d680, 0x30dec38, 0x0, 0x0, 0x0, 0x0)
	/home/matic/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20210419165708-5d75f0b3ea99/server/start.go:117 +0x154
github.com/spf13/cobra.(*Command).execute(0xc00110d680, 0x30dec38, 0x0, 0x0, 0xc00110d680, 0x30dec38)
	/home/matic/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc001086280, 0x1c18293, 0x8, 0xc00011b740)
	/home/matic/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/matic/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/matic/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
github.com/maticnetwork/heimdall/cmd/heimdalld/cmd.Execute(0xc001086280, 0x21d61d8, 0xc00000fad0)
	/home/matic/sources/heimdall/cmd/heimdalld/cmd/root.go:131 +0x165
main.main()
	/home/matic/sources/heimdall/cmd/heimdalld/main.go:11 +0x2a

```

Most likely it is due to genesis file, attached. I assembled this genesis file myself fixing the genesis file from `launch` repo (because is not up to date with heimdalld) , however if I generate default genesis file with `init` command, I get the same error. My point is, golang shouldn't panic if I provide incorrect genesis file, that's the problem I am reporting.
P.S.
if you can give the link to the latest genesis file that would be very good.

Genesis file:
```

{
  "genesis_time": "2020-06-04T10:47:20.806665Z",
  "chain_id": "heimdall-80001",
  "initial_height": "1",
  "consensus_params": {
    "block": {
      "max_bytes": "22020096",
      "max_gas": "-1",
      "time_iota_ms": "1000"
    },
    "evidence": {
	    "max_age_num_blocks": "100000",
	    "max_age_duration": "172800000000000",
	    "max_bytes": "1048576"
    },
    "validator": {
      "pub_key_types": [
        "secp256k1"
      ]
    },
 	"version": {}
  },
  "app_hash": "",
  "app_state": {
    "auth": {
      "params": {
        "max_memo_characters": "256",
        "tx_sig_limit": "7",
        "tx_size_cost_per_byte": "10",
        "sig_verify_cost_ed25519": "590",
        "sig_verify_cost_secp256k1": "1000"
      },
      "accounts": [
        {
          "address": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
          "coins": [
            {
              "denom": "matic",
              "amount": "1000000000000000000000"
            }
          ],
          "sequence_number": "0",
          "account_number": "0",
          "module_name": "",
          "module_permissions": null
        },
        {
          "address": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
          "coins": [
            {
              "denom": "matic",
              "amount": "1000000000000000000000"
            }
          ],
          "sequence_number": "0",
          "account_number": "0",
          "module_name": "",
          "module_permissions": null
        },
        {
          "address": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
          "coins": [
            {
              "denom": "matic",
              "amount": "1000000000000000000000"
            }
          ],
          "sequence_number": "0",
          "account_number": "0",
          "module_name": "",
          "module_permissions": null
        },
        {
          "address": "0xf903ba9e006193c1527bfbe65fe2123704ea3f99",
          "coins": [
            {
              "denom": "matic",
              "amount": "1000000000000000000000"
            }
          ],
          "sequence_number": "0",
          "account_number": "0",
          "module_name": "",
          "module_permissions": null
        },
        {
          "address": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
          "coins": [
            {
              "denom": "matic",
              "amount": "1000000000000000000000"
            }
          ],
          "sequence_number": "0",
          "account_number": "0",
          "module_name": "",
          "module_permissions": null
        }
      ]
    },
    "bank": {
        "params": {
        	"send_enabled": [],
    	  	"default_send_enabled": true
      	},
      "balances": [],
      "supply": [],
      "denom_metadata": []
    },
    "bor": {
      "params": {
        "sprint_duration": "64",
        "span_duration": "6400",
        "producer_count": "11"
      },
      "spans": [
        {
          "span_id": "0",
          "start_block": "0",
          "end_block": "255",
          "validator_set": {
            "validators": [
              {
                "ID": "5",
                "startEpoch": "0",
                "endEpoch": "0",
                "nonce": "1",
                "power": "10000",
                "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
                "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
                "last_updated": "",
                "jailed": false,
                "accum": "-40000"
              },
              {
                "ID": "2",
                "startEpoch": "0",
                "endEpoch": "0",
                "nonce": "1",
                "power": "10000",
                "pubKey": "0x04888a737a003f4e522ccf23bd9980fdbe7ef2b54365249deba0f9acd45279d66355b1864173b2cf9e75a1cbfb45e65a1a72b9ea76e47aa4bd50d79772ef301769",
                "signer": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
                "last_updated": "",
                "jailed": false,
                "accum": "10000"
              },
              {
                "ID": "1",
                "startEpoch": "0",
                "endEpoch": "0",
                "nonce": "1",
                "power": "10000",
                "pubKey": "0x040bec8102c221c7cfff3e250bb6cc01c3b9a3964fb1bf4d53e91905320eef09595acb09ee0950e7374ec19488ff2523f186f6b1a9164c78dba8602e4e3c4eb013",
                "signer": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
                "last_updated": "",
                "jailed": false,
                "accum": "10000"
              },
              {
                "ID": "3",
                "startEpoch": "0",
                "endEpoch": "0",
                "nonce": "1",
                "power": "10000",
                "pubKey": "0x04f3f18a027c929380417d2bd7d2a489cb662d4977e9daff335bc51f23c1c5f5f468aa19c6c8e937a745462ef2550bce42e4f38608dffb5a06e7b9d27d964cffee",
                "signer": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
                "last_updated": "",
                "jailed": false,
                "accum": "10000"
              },
              {
                "ID": "4",
                "startEpoch": "0",
                "endEpoch": "0",
                "nonce": "1",
                "power": "10000",
                "pubKey": "0x04dcd2883416e7b8663caafbfc885e757b0ea809657df8d6f322f01a0c5a11fd033bf13d3e0d5e88feff92ba415d32d626e3f7d9dd7b5ec7c2fef8ded83d660ac2",
                "signer": "0xf903ba9e006193c1527bfbe65fe2123704ea3f99",
                "last_updated": "",
                "jailed": false,
                "accum": "10000"
              }
            ],
            "proposer": {
              "ID": "5",
              "startEpoch": "0",
              "endEpoch": "0",
              "nonce": "1",
              "power": "10000",
              "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
              "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
              "last_updated": "",
              "jailed": false,
              "accum": "-40000"
            }
          },
          "selected_producers": [
            {
              "ID": "5",
              "startEpoch": "0",
              "endEpoch": "0",
              "nonce": "1",
              "power": "10000",
              "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
              "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
              "last_updated": "",
              "jailed": false,
              "accum": "-40000"
            },
            {
              "ID": "2",
              "startEpoch": "0",
              "endEpoch": "0",
              "nonce": "1",
              "power": "10000",
              "pubKey": "0x04888a737a003f4e522ccf23bd9980fdbe7ef2b54365249deba0f9acd45279d66355b1864173b2cf9e75a1cbfb45e65a1a72b9ea76e47aa4bd50d79772ef301769",
              "signer": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
              "last_updated": "",
              "jailed": false,
              "accum": "10000"
            },
            {
              "ID": "1",
              "startEpoch": "0",
              "endEpoch": "0",
              "nonce": "1",
              "power": "10000",
              "pubKey": "0x040bec8102c221c7cfff3e250bb6cc01c3b9a3964fb1bf4d53e91905320eef09595acb09ee0950e7374ec19488ff2523f186f6b1a9164c78dba8602e4e3c4eb013",
              "signer": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
              "last_updated": "",
              "jailed": false,
              "accum": "10000"
            },
            {
              "ID": "3",
              "startEpoch": "0",
              "endEpoch": "0",
              "nonce": "1",
              "power": "10000",
              "pubKey": "0x04f3f18a027c929380417d2bd7d2a489cb662d4977e9daff335bc51f23c1c5f5f468aa19c6c8e937a745462ef2550bce42e4f38608dffb5a06e7b9d27d964cffee",
              "signer": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
              "last_updated": "",
              "jailed": false,
              "accum": "10000"
            }
          ],
          "bor_chain_id": "80001"
        }
      ]
    },
    "chainmanager": {
      "params": {
        "mainchain_tx_confirmations": "6",
        "maticchain_tx_confirmations": "10",
        "chain_params": {
          "bor_chain_id": "80001",
          "matic_token_address": "0x499d11E0b6eAC7c0593d8Fb292DCBbF815Fb29Ae",
          "staking_manager_address": "0x4864d89DCE4e24b2eDF64735E014a7E4154bfA7A",
          "slash_manager_address": "0x93D8f8A1A88498b258ceb69dD82311962374269C",
          "root_chain_address": "0x2890bA17EfE978480615e330ecB65333b880928e",
          "staking_info_address": "0x318EeD65F064904Bc6E0e3842940c5972BC8E38f",
          "state_sender_address": "0xEAa852323826C71cd7920C3b4c007184234c3945",
          "state_receiver_address": "0x0000000000000000000000000000000000001001",
          "validator_set_address": "0x0000000000000000000000000000000000001000"
        }
      }
    },
    "checkpoint": {
      "params": {
        "checkpoint_buffer_time": "1000000000000",
        "avg_checkpoint_length": "256",
        "max_checkpoint_length": "1024",
        "child_chain_block_interval": "10000"
      },
      "buffered_checkpoint": null,
      "last_no_ack": "0",
      "ack_count": "0",
      "checkpoints": null
    },
    "clerk": {
      "event_records": [],
      "record_sequences": null
    },
    "gov": {
      "starting_proposal_id": "1",
      "deposits": null,
      "votes": null,
      "proposals": null,
      "deposit_params": {
        "min_deposit": [
          {
            "denom": "matic",
            "amount": "10000000000000000000"
          }
        ],
        "max_deposit_period": "3600000000000"
      },
      "voting_params": {
        "voting_period": "3600000000000"
      },
      "tally_params": {
        "quorum": "0.334000000000000000",
        "threshold": "0.500000000000000000",
        "veto": "0.334000000000000000"
      }
    },
    "params": null,
    "sidechannel": {
      "past_commits": []
    },
    "slashing": {
      "params": {
        "signed_blocks_window": "100",
        "min_signed_per_window": "0.500000000000000000",
        "downtime_jail_duration": "600000000000",
        "slash_fraction_double_sign": "0.050000000000000000",
        "slash_fraction_downtime": "0.010000000000000000",
        "slash_fraction_limit": "0.333333333333333333",
        "jail_fraction_limit": "0.333333333333333333",
        "max_evidence_age": "120000000000",
        "enable_slashing": false
      },
      "signing_infos": {
        "2": {
          "valID": "2",
          "startHeight": "0",
          "indexOffset": "0"
        },
        "3": {
          "valID": "3",
          "startHeight": "0",
          "indexOffset": "0"
        },
        "4": {
          "valID": "4",
          "startHeight": "0",
          "indexOffset": "0"
        },
        "5": {
          "valID": "5",
          "startHeight": "0",
          "indexOffset": "0"
        },
        "1": {
          "valID": "1",
          "startHeight": "0",
          "indexOffset": "0"
        }
      },
      "missed_blocks": {},
      "buffer_val_slash_info": null,
      "tick_val_slash_info": null,
      "tick_count": "0"
    },
    "staking": {
      "validators": [
        {
          "ID": "1",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x040bec8102c221c7cfff3e250bb6cc01c3b9a3964fb1bf4d53e91905320eef09595acb09ee0950e7374ec19488ff2523f186f6b1a9164c78dba8602e4e3c4eb013",
          "signer": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
          "last_updated": "",
          "jailed": false,
          "accum": "0"
        },
        {
          "ID": "2",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x04888a737a003f4e522ccf23bd9980fdbe7ef2b54365249deba0f9acd45279d66355b1864173b2cf9e75a1cbfb45e65a1a72b9ea76e47aa4bd50d79772ef301769",
          "signer": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
          "last_updated": "",
          "jailed": false,
          "accum": "0"
        },
        {
          "ID": "3",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x04f3f18a027c929380417d2bd7d2a489cb662d4977e9daff335bc51f23c1c5f5f468aa19c6c8e937a745462ef2550bce42e4f38608dffb5a06e7b9d27d964cffee",
          "signer": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
          "last_updated": "",
          "jailed": false,
          "accum": "0"
        },
        {
          "ID": "4",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x04dcd2883416e7b8663caafbfc885e757b0ea809657df8d6f322f01a0c5a11fd033bf13d3e0d5e88feff92ba415d32d626e3f7d9dd7b5ec7c2fef8ded83d660ac2",
          "signer": "0xf903ba9e006193c1527bfbe65fe2123704ea3f99",
          "last_updated": "",
          "jailed": false,
          "accum": "0"
        },
        {
          "ID": "5",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
          "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
          "last_updated": "",
          "jailed": false,
          "accum": "0"
        }
      ],
      "current_val_set": {
        "validators": [
          {
            "ID": "5",
            "startEpoch": "0",
            "endEpoch": "0",
            "nonce": "1",
            "power": "10000",
            "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
            "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
            "last_updated": "",
            "jailed": false,
            "accum": "-40000"
          },
          {
            "ID": "2",
            "startEpoch": "0",
            "endEpoch": "0",
            "nonce": "1",
            "power": "10000",
            "pubKey": "0x04888a737a003f4e522ccf23bd9980fdbe7ef2b54365249deba0f9acd45279d66355b1864173b2cf9e75a1cbfb45e65a1a72b9ea76e47aa4bd50d79772ef301769",
            "signer": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
            "last_updated": "",
            "jailed": false,
            "accum": "10000"
          },
          {
            "ID": "1",
            "startEpoch": "0",
            "endEpoch": "0",
            "nonce": "1",
            "power": "10000",
            "pubKey": "0x040bec8102c221c7cfff3e250bb6cc01c3b9a3964fb1bf4d53e91905320eef09595acb09ee0950e7374ec19488ff2523f186f6b1a9164c78dba8602e4e3c4eb013",
            "signer": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
            "last_updated": "",
            "jailed": false,
            "accum": "10000"
          },
          {
            "ID": "3",
            "startEpoch": "0",
            "endEpoch": "0",
            "nonce": "1",
            "power": "10000",
            "pubKey": "0x04f3f18a027c929380417d2bd7d2a489cb662d4977e9daff335bc51f23c1c5f5f468aa19c6c8e937a745462ef2550bce42e4f38608dffb5a06e7b9d27d964cffee",
            "signer": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
            "last_updated": "",
            "jailed": false,
            "accum": "10000"
          },
          {
            "ID": "4",
            "startEpoch": "0",
            "endEpoch": "0",
            "nonce": "1",
            "power": "10000",
            "pubKey": "0x04dcd2883416e7b8663caafbfc885e757b0ea809657df8d6f322f01a0c5a11fd033bf13d3e0d5e88feff92ba415d32d626e3f7d9dd7b5ec7c2fef8ded83d660ac2",
            "signer": "0xf903ba9e006193c1527bfbe65fe2123704ea3f99",
            "last_updated": "",
            "jailed": false,
            "accum": "10000"
          }
        ],
        "proposer": {
          "ID": "5",
          "startEpoch": "0",
          "endEpoch": "0",
          "nonce": "1",
          "power": "10000",
          "pubKey": "0x04a267a9c19d2bc85bc8d7419e864eded7e193581fd98915d07cae86fd8a03aeb66ed87b02003a7897654562d29677221808d7790b300e69162ad86c1b7b24cd07",
          "signer": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
          "last_updated": "",
          "jailed": false,
          "accum": "-40000"
        }
      },
      "staking_sequences": null
    },
    "supply": {
      "supply": {
        "total": []
      }
    },
    "topup": {
      "tx_sequences": null,
      "dividend_accounts": [
        {
          "user": "0xc26880a0af2ea0c7e8130e6ec47af756465452e8",
          "feeAmount": "0"
        },
        {
          "user": "0xbe188d6641e8b680743a4815dfa0f6208038960f",
          "feeAmount": "0"
        },
        {
          "user": "0xc275dc8be39f50d12f66b6a63629c39da5bae5bd",
          "feeAmount": "0"
        },
        {
          "user": "0xf903ba9e006193c1527bfbe65fe2123704ea3f99",
          "feeAmount": "0"
        },
        {
          "user": "0x928ed6a3e94437bbd316ccad78479f1d163a6a8c",
          "feeAmount": "0"
        }
      ]
    }
  }
}
```

**Comment by temaniarpit27** [comment]
Please use the latest version and reopen if required
