### ISSUE TITLE
panic: unexpected end of JSON input

### ISSUE THREAD

**Issue by ebadiere** [maticnetwork/heimdall#803]
I followed these instructions to set up a validator node: https://docs.polygon.technology/docs/validate/validate/run-validator-binaries.  I got to the "Start the Heimdall service:" , and when I started the service I got the following message:

```
I[2022-03-27|08:23:55.692] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
panic: unexpected end of JSON input```

I suspect it's not finding the genesis.json file.  The file is in my $HOME/.hemidaldd/config directory.  

**Heimdall version** (use `heimdall version` or `git rev-parse --verify HEAD` if installed from source):
I can't run a `heimdall version`.  Could that be the issue?  It built a heimdalld binary when I ran the `make install` command.
```
eric@eric1:~$ heimdall version
-bash: heimdall: command not found
eric@eric1:~$ heimdalld version
0.2.8

eric@eric1:~/src/heimdall$ git rev-parse --verify HEAD
3cdebf177775bf697945636b4f07fe9a79b642be
eric@eric1:~/src/heimdall$
```

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal```

- **Install tools**:
Just the build tools listed as the first step in the installation instructions.

The heimdalld process didn't start up and start syncing the blockchain.

I expected the heimdalld process to start up and start syncing the blockchain.

**Have you tried the latest version**: yes/no - yes

**How to reproduce it** (as minimally and precisely as possible):  To reproduce follow the instructions to the "Start the Heimdall service:" step, then try to start.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:  When I start with debug:

```
eric@eric1:~$ /home/eric/go/bin/heimdalld --log_level debug start
I[2022-03-27|08:23:55.678] starting ABCI with Tendermint                module=main
I[2022-03-27|08:23:55.691] Starting multiAppConn                        module=proxy impl=multiAppConn
I[2022-03-27|08:23:55.691] Starting localClient                         module=abci-client connection=query impl=localClient
I[2022-03-27|08:23:55.691] Starting localClient                         module=abci-client connection=mempool impl=localClient
I[2022-03-27|08:23:55.691] Starting localClient                         module=abci-client connection=consensus impl=localClient
I[2022-03-27|08:23:55.691] Starting EventBus                            module=events impl=EventBus
I[2022-03-27|08:23:55.691] Starting PubSub                              module=pubsub impl=PubSub
I[2022-03-27|08:23:55.692] Starting IndexerService                      module=txindex impl=IndexerService
I[2022-03-27|08:23:55.692] ABCI Handshake App Info                      module=consensus height=0 hash= software-version= protocol-version=0
I[2022-03-27|08:23:55.692] ABCI Replay Blocks                           module=consensus appHeight=0 storeHeight=0 stateHeight=0
panic: unexpected end of JSON input

goroutine 1 [running]:
github.com/maticnetwork/heimdall/app.(*HeimdallApp).InitChainer(_, {{0x178a668, 0xc0000400b0}, {0x17a4290, 0xc0005d7800}, {{0x0, 0x0, {}, {0x0, 0x0, ...}, ...}, ...}, ...}, ...)
	/home/eric/src/heimdall/app/app.go:510 +0x79a
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000173e00, {{0x203727ff, 0xed9d1b5f3, 0x0}, {0xc0005fed50, 0xf}, 0xc0005d7740, {0x23f85c8, 0x0, 0x0}, ...})
	/home/eric/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20220311095845-81690c6a53e7/baseapp/baseapp.go:405 +0x2f8
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000eb80c0, {{0x203727ff, 0xed9d1b5f3, 0x0}, {0xc0005fed50, 0xf}, 0xc0005d7740, {0x23f85c8, 0x0, 0x0}, ...})
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/abci/client/local_client.go:223 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x0, {{0x203727ff, 0xed9d1b5f3, 0x0}, {0xc0005fed50, 0xf}, 0xc0005d7740, {0x23f85c8, 0x0, 0x0}, ...})
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/proxy/app_conn.go:68 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xa, 0x0}, {0xc0005fefc8, 0x6}}, {0xc0005fefe0, 0xf}, 0x0, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/consensus/replay.go:311 +0xcc4
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000dbafc8, {0x17a8b60, 0xc000e89030})
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/consensus/replay.go:269 +0x4c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xa, 0x0}, {0xc0005fefc8, 0x6}}, {0xc0005fefe0, 0xf}, 0x0, 0x0, ...}, ...)
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/node/node.go:275 +0x1a5
github.com/tendermint/tendermint/node.NewNode(0xc000173400, {0x178b3f8, 0xc000eccfa0}, 0xc000bfba40, {0x17674c0, 0xc000ca2540}, 0xc, 0x11a8e40, 0xc000bfbb20, {0x178b238, ...}, ...)
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/node/node.go:582 +0x309
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc00000e8d0, 0x158f978)
	/home/eric/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20220311095845-81690c6a53e7/server/start.go:152 +0x3f9
github.com/cosmos/cosmos-sdk/server.StartCmd.func1(0xc000ec0c80, {0xc00056b600, 0x0, 0x2})
	/home/eric/go/pkg/mod/github.com/maticnetwork/cosmos-sdk@v0.37.5-0.20220311095845-81690c6a53e7/server/start.go:65 +0x7f
github.com/spf13/cobra.(*Command).execute(0xc000ec0c80, {0xc00056b5c0, 0x2, 0x2})
	/home/eric/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:826 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000ea1b80)
	/home/eric/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/eric/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
github.com/tendermint/tendermint/libs/cli.Executor.Execute({0xc000ea1b80, 0x158fc40})
	/home/eric/go/pkg/mod/github.com/maticnetwork/tendermint@v0.26.0-dev0.0.20220311091200-3ea059b213ed/libs/cli/setup.go:89 +0x36
main.main()
	/home/eric/src/heimdall/cmd/heimdalld/main.go:114 +0x3fe
```

**Config (you can paste only the changes you've made)**: None

**node command runtime flags**:  /home/eric/go/bin/heimdalld --log_level debug start

**`/dump_consensus_state` output for consensus bugs**

**Anything else we need to know**: I am using the genesis.json from the launch/mainnet-v1/without-sentry/heimdall/config directory: https://github.com/maticnetwork/launch/blob/master/mainnet-v1/without-sentry/heimdall/config/genesis.json

**Comment by 0xKrishna** [comment]
Why this path `$HOME/.hemidaldd/config directory.`
There is a typo, By default it should be `$HOME/.heimdalld/config`

**Comment by temaniarpit27** [comment]
Please check and reopen if required
